### ISSUE TITLE
Dialogue

### ISSUE THREAD

**Issue by csobel** [corychang/Patient#20]

**Comment by csobel** [comment]
Provides subtitles for dialogue. See http://docs.unity3d.com/Manual/GUIScriptingGuide.html for how to create and render the dialogue to the screen. May be tied in with #17 as we could play a generic talking sound while dialogue is being rendered

**Comment by corychang** [comment]
For a v0, we can just have the text appear, and disappear after some time. Later, we'll want flowing text.

**Comment by dighjd12** [comment]
I can work on this :)

**Comment by dighjd12** [comment]
-kayla
